# Generated by Django 4.0.1 on 2022-04-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('fac_code', models.CharField(max_length=7, primary_key=b'I01\n', serialize=False)),
                ('fac_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='resource',
            fields=[
                ('room_no', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('sub_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=30)),
            ],
        ),
    ]
