# Generated by Django 4.0.1 on 2022-04-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fac_code',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
