# Generated by Django 4.0.1 on 2022-04-09 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_alter_faculty_fac_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_alloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('lec_type', models.CharField(max_length=10)),
                ('faculty_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='teach',
            field=models.ManyToManyField(blank=True, through='selection.faculty_alloc', to='selection.faculty'),
        ),
        migrations.AddField(
            model_name='faculty_alloc',
            name='subcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='faculty_alloc',
            unique_together={('semester', 'subcode', 'faculty_n')},
        ),
    ]
