# Generated by Django 4.0.1 on 2022-04-09 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0003_faculty_alloc_subject_teach_faculty_alloc_subcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('Theory_Priority1', models.CharField(max_length=10)),
                ('Practical_Priority1', models.CharField(max_length=10)),
                ('Theory_Priority2', models.CharField(max_length=10)),
                ('Practical_Priority2', models.CharField(max_length=10)),
                ('Theory_Priority3', models.CharField(max_length=10)),
                ('Practical_Priority3', models.CharField(max_length=10)),
                ('fac_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.faculty')),
            ],
        ),
    ]
