# Generated by Django 4.0.1 on 2022-04-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0005_remove_subject_teach_delete_faculty_alloc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='Practical_Priority2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='priority',
            name='Practical_Priority3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='priority',
            name='Theory_Priority2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='priority',
            name='Theory_Priority3',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
