# Generated by Django 4.0.1 on 2022-04-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('selection', '0002_alter_faculty_fac_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_alloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(max_length=2)),
                ('lec_type', models.CharField(max_length=10)),
                ('faculty_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.faculty')),
                ('subcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.subject')),
            ],
            options={
                'unique_together': {('semester', 'subcode', 'faculty_n')},
            },
        ),
    ]
