# Generated by Django 4.0.1 on 2022-04-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_allocation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='faculty_alloc',
        ),
    ]
