# Generated by Django 4.0.1 on 2022-04-09 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('selection', '0005_remove_subject_teach_delete_faculty_alloc'),
        ('faculty_allocation', '0002_delete_faculty_alloc'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_alloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.IntegerField()),
                ('lecture_Type', models.CharField(max_length=10)),
                ('Faculty_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.faculty')),
                ('Subject_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.subject')),
            ],
            options={
                'unique_together': {('Semester', 'Subject_Code', 'Faculty_Name')},
            },
        ),
    ]
